services:
  - type: web
    name: html-converter-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: API_ID
        value: 36123528
        scope: run
      - key: API_HASH
        value: "7f77eb79febe2b7cf5d33d6d57bc8ac0"
        scope: run
      - key: BOT_TOKEN
        value: "8564887159:AAFk2GpNH96K_G0Vm1CfoOX3EX0GBWzeKoQ"
        scope: run
      - key: LOG_CHANNEL
        value: -1003891933514
        scope: run
